events {}

http {
    server {
        listen 443 ssl;
        server_name admin.noti0n.com;

        ssl_certificate /etc/letsencrypt/live/admin.noti0n.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/admin.noti0n.com/privkey.pem;

        location / {
            proxy_pass https://gophish:3333;
            proxy_ssl_verify off;
        }
    }

    server {
        listen 443 ssl;
        server_name noti0n.com;

        ssl_certificate /etc/letsencrypt/live/noti0n.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/noti0n.com/privkey.pem;

        root /web;
        index index.html;

        location /login/ {
            proxy_pass http://gophish:80/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_ssl_verify off;
        }

        location /hacked/ {
            try_files /hacked.html =404;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }

    server {
        listen 80;
        server_name noti0n.com admin.noti0n.com;
        return 301 https://$host$request_uri;
    }
}

