events {}

http {
    server {
        listen 443 ssl;
        server_name admin.noti0n.com;

        ssl_certificate /etc/letsencrypt/live/admin.noti0n.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/admin.noti0n.com/privkey.pem;

        location / {
            proxy_pass https://gophish:3333;
            proxy_ssl_verify off;
        }
    }

    server {
        listen 443 ssl;
        server_name noti0n.com;

        ssl_certificate /etc/letsencrypt/live/admin.noti0n.com/fullchain.pem; # You can reuse the cert or make a new one later
        ssl_certificate_key /etc/letsencrypt/live/admin.noti0n.com/privkey.pem;

        location / {
            proxy_pass http://gophish:80;
        }
    }

    server {
        listen 80;
        server_name admin.noti0n.com noti0n.com;
        return 301 https://$host$request_uri;
    }
}
